### ISSUE TITLE
Consider removing interface

### ISSUE THREAD

**Issue by TomaszStojek** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#103]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Jump.java#L1

If only player interfaces with it, consider removing this class, unless more will use it

**Comment by BhavnoorSaroya** [comment]
Duplicate see #87
