### ISSUE TITLE
Can use OS packages in java.lang or Path

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#104]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Window.java#L41

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html

**Comment by BhavnoorSaroya** [comment]
completed in #66
