### ISSUE TITLE
Could possibly refactor this as it is repetitive

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#105]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Enemy.java#L81

**Comment by BhavnoorSaroya** [comment]
Refactored Enemies to use window.circle and and window.triangle methods, reducing the lines mentioned here, taken care of in another issue
