### ISSUE TITLE
Empty interface - add methods or consider removing

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#109]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Edible.java#L4

**Comment by BhavnoorSaroya** [comment]
duplicate see #82
