### ISSUE TITLE
If statement nested in switch, consider adding additional cases or just use if statement

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#122]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Window.java#L98

**Comment by BhavnoorSaroya** [comment]
not sure what you mean, need to check multiple cases where certain things are happening, refactoring to just switch or just if statements would require more verbosity and repeating code, breaking the fundamental principle DRY (don't repeat yourself)
