### ISSUE TITLE
Implement coin class and add javadocs

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#123]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Coin.java#L1

**Comment by BhavnoorSaroya** [comment]
Duplicate see #36 and #74
