### ISSUE TITLE
Define collided method in the class that implements Collided

### ISSUE THREAD

**Issue by CyrusVillaruz** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#125]
Also, was it supposed to be called "Collidable", since it seems to handle all the collision logic

**Comment by CyrusVillaruz** [comment]
Alternatively, could make Collided an abstract class

**Comment by BhavnoorSaroya** [comment]
The class in question has default method that does not need to be redefined by its implementers in this case. See #96 for more info.  Will refactor name

**Comment by BhavnoorSaroya** [comment]
the remainder of this issue is a duplicate see #110
