### ISSUE TITLE
Add documentation for hashmap class 

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#126]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/MyHashMap.java#L5

**Comment by BhavnoorSaroya** [comment]
Will document all classes asap see #74
