### ISSUE TITLE
Defined method in Interface

### ISSUE THREAD

**Issue by TomaszStojek** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#127]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Collided.java#L9

Interfaces should should not have defined methods

**Comment by BhavnoorSaroya** [comment]
> Interfaces should should not have defined methods

Yes they should, as of java 8, interfaced are able to provide a default implementation of a method, see #96 for a longer explanation.
