### ISSUE TITLE
Unclear usage for this entire class. Either better documentation or clearer implementation

### ISSUE THREAD

**Issue by qowier** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#128]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/MyHashMap.java#L1

**Comment by BhavnoorSaroya** [comment]
Hashmap is now implemented in window.java prior implementation used array list and this was slow. see #170
