### ISSUE TITLE
HashMap class javadocs

### ISSUE THREAD

**Issue by CyrusVillaruz** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#129]
I know you mentioned that it will be used in the future, so I will hold off of giving that issue.

How are the methods and constructors going to be used with other classes specifically?

**Comment by BhavnoorSaroya** [comment]
> How are the methods and constructors going to be used with other classes specifically? 

Hashmap is intented to replace the current use of arraylist entirely in window, very little changed should be needed in window, as the same method names will be used. as for javadocs see #74
