### ISSUE TITLE
lacking further implementation. unclear use

### ISSUE THREAD

**Issue by qowier** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#130]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Jump.java#L3-L5

**Comment by BhavnoorSaroya** [comment]
Duplicate See Issue #87
