### ISSUE TITLE
Unused class in final executable

### ISSUE THREAD

**Issue by qowier** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#131]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Coin.java#L7-L12

**Comment by BhavnoorSaroya** [comment]
Duplicate see #82
