### ISSUE TITLE
What is the point of a do nothing method?

### ISSUE THREAD

**Issue by qowier** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#133]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/StartPage.java#L63-L66

**Comment by BhavnoorSaroya** [comment]
Duplicate see #91
