### ISSUE TITLE
Consider adding a test case for inputs during a jump.

### ISSUE THREAD

**Issue by qowier** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#134]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/test/java/org/bcit/comp2522/project/PlayerTest.java#L1

Does the jump continue? Does it "refresh"? Does it ignore? etc

**Comment by BhavnoorSaroya** [comment]
see #177
