### ISSUE TITLE
Add a package statement 

### ISSUE THREAD

**Issue by YejuJ** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#143]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/test/java/org/bcit/comp2522/project/SpriteTest.java#L1

**Comment by yuvraajchouhan** [comment]
Resolved in issue #179
