### ISSUE TITLE
Get rid of unused import statement

### ISSUE THREAD

**Issue by YejuJ** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#144]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/test/java/org/bcit/comp2522/project/ButtonTest.java#L3

https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/test/java/org/bcit/comp2522/project/EnemyTest.java#L6

**Comment by BhavnoorSaroya** [comment]
Duplicate see #117
