### ISSUE TITLE
The condition for if statement could be simplified

### ISSUE THREAD

**Issue by YejuJ** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#146]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Collided.java#L9

**Comment by BhavnoorSaroya** [comment]
How? Will reopen the issue if it can, but this would require either not using getters or increasing versbosity???
