### ISSUE TITLE
Check load factor before rehashing: Modify the add method to check if the load factor exceeds the threshold before rehashing.

### ISSUE THREAD

**Issue by Bingdididi** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#151]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/MyHashMap.java#L71-L85

**Comment by BhavnoorSaroya** [comment]
This is already being done see issue #53
