### ISSUE TITLE
Add remove and containsKey methods: Implement the remove and containsKey methods for better functionality of the HashMap.

### ISSUE THREAD

**Issue by Bingdididi** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#152]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/MyHashMap.java#L101

**Comment by BhavnoorSaroya** [comment]
added containsKey, remove method already implemented in another issue see issue #170
