### ISSUE TITLE
Considering implementing the jump class completely

### ISSUE THREAD

**Issue by Bingdididi** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#153]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/Jump.java#L1-L5

**Comment by BhavnoorSaroya** [comment]
closed marked as duplicate
