### ISSUE TITLE
Handle potential exceptions: Add error handling for potential exceptions that may occur when connecting to the database or performing operations, such as using try-catch blocks.

### ISSUE THREAD

**Issue by Bingdididi** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#155]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/4640705d95f4e58bd482424d7f45d638b509612f/src/main/java/org/bcit/comp2522/project/DatabaseHandler.java#L50-L62

**Comment by BhavnoorSaroya** [comment]
This is a duplicate see #140
