### ISSUE TITLE
implement w, SPACE and up arrow in keyPressed Method for Window Class

### ISSUE THREAD

**Issue by yuvraajchouhan** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#45]
Assigned to myself as this comes under movement for Player. Will also get rid of the left, right case as player auto moves to the right as the map goes on.

**Comment by BhavnoorSaroya** [comment]
completed in another pull request, same branch

**Comment by BhavnoorSaroya** [comment]
excellent catch, every UX thing matters!
