### ISSUE TITLE
Create JavaDocs

### ISSUE THREAD

**Issue by TomaszStojek** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#74]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/MyHashMap.java#L5

**Comment by BhavnoorSaroya** [comment]
completed see #73
