### ISSUE TITLE
remove test print lines

### ISSUE THREAD

**Issue by TomaszStojek** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#77]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Window.java#L95

Remove console logs print statements after testing is completed

**Comment by BhavnoorSaroya** [comment]
Done in #212
