### ISSUE TITLE
Can simplify setter params in window class

### ISSUE THREAD

**Issue by CyrusVillaruz** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#84]
Not a major thing, but can set local variables representing the player's position, and passing those in.

For example, in line 145 of the Window class, you could create local variables for the player's x, y, and z positions, and pass those in instead.

`player.setPosition(player.getPosition().x, player.getPosition().y - (player.getSize() / 2), player.getPosition().z);` 
-> `player.setPosition(playerXpos, playerYpos, playerZpos);`

**Comment by BhavnoorSaroya** [comment]
This specific section of code was removed, however due to the volatile nature of the size variable and how often is it mutated, a variable reference to keep it updated would likely decrease readability, marking this as closed but will keep in mind
