### ISSUE TITLE
UnUsed class

### ISSUE THREAD

**Issue by TomaszStojek** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#89]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/Coin.java#L7

What is this for

**Comment by BhavnoorSaroya** [comment]
Yet to be implemented, see issue #6
