### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by elsaho** [COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej#98]
https://github.com/COMP2522/project-bhavnoor-yuvraaj-won-leo-gurtej/blob/eb4a15c5ebf37ee26073955932e0d7a6312599c5/src/main/java/org/bcit/comp2522/project/StartPage.java#L21

**Comment by BhavnoorSaroya** [comment]
Duplicate see #78
